package com.mengbo.mbCan.defines;

/* loaded from: classes.dex */
public enum MBCanDataType {
    eMBCAN_VEHICLE_SPEED(1),
    eMBCAN_VEHICLE_TURNLIGHT(2),
    eMBCAN_VEHICLE_STEERING_ANGLE(3),
    eMBCAN_VEHICLE_WHEEL(4),
    eMBCAN_VEHICLE_DOOR(5),
    eMBCAN_VEHICLE_ACCSTATUS(6),
    eMBCAN_RADARSENSOR(7),
    eMBCAN_SYSTEMMODE(8),
    eMBCAN_HARDKEY(9),
    eMBCAN_SEAT_STATUS(10),
    eMBCAN_RCTA_ALARM(11),
    eMBCAN_VEHICLE_FUELLEVEL(12),
    eMBCAN_DVR_STATUS(13),
    eMBCAN_WPC_STATUS(14),
    eMBCAN_SEAT_BELT_STATUS(15),
    eMBCAN_VEHICLE_TOTALODOMETER(16),
    eMBCAN_AVM_STATUS(17),
    eMBCAN_CHIME_STATUS(18),
    eMBCAN_RADIO_FREQUENCYINFO(19),
    eMBCAN_VEHICLE_GEAR(20),
    eMBCAN_VEHICLE_BCM_STATUS(21),
    eMBCAN_VEHICLE_ENGINE(22),
    eMBCAN_CFG_AUDIO(23),
    eMBCAN_CFG_VEHICLE(24),
    eMBCAN_CFG_DMS(25),
    eMBCAN_UPGRADE_PROGRESS(26),
    eMBCAN_DTC(27),
    eMBCAN_PM25INFO(28),
    eMBCAN_VEHICLE_ENGINE_GEAR(29),
    eMBCAN_RADIO_PROGRAMSTATE(30),
    eMBCAN_INSTRUMENT_CMDREPLY(31),
    eMBCAN_USB_DEVICE(32),
    eMBCAN_UART_TEST_RESULT(33),
    eMBCAN_VEHICLE_TIRE(34),
    eMBCAN_VEHICLE_FUELTANK(35),
    eMBCAN_VEHICLE_GASPED_STATUS(36),
    eMBCAN_VEHICLE_AQS_STATUS(37),
    eMBCAN_VEHICLE_EXTERNAL_TEMP_RAW(38),
    eMBCAN_VEHICLE_EBS_SOC(39),
    eMBCAN_VEHICLE_LKA_STATUS(40),
    eMBCAN_VEHICLE_FRM_INFO(41),
    eMBCAN_VEHICLE_ICM_INFO(42),
    eMBCAN_VEHICLE_ICM_FAULT_INFO(43),
    eMBCAN_VEHICLE_ICM_DRIVE_INFO(44),
    eMBCAN_VEHICLE_CEM_FRAG(45),
    eMBCAN_DOW_ALARM(46),
    eMBCAN_BSD_ALARM(47),
    eMBCAN_ICM_TRIP_INFO(48),
    eMBCAN_ICM_ALARM_INFO(49),
    eMBCAN_VEHICLE_INVERTER_STATUS(50),
    eMBCAN_VEHICLE_DVR_PARAM(51),
    eMBCAN_VEHICLE_EPB_STATUS(52),
    eMBCAN_VEHICLE_CONSUMPTION(53),
    eMBCAN_CHARGING_RESERVE(54),
    eMBCAN_COUNT(55);

    private int value;

    MBCanDataType(int i) {
        this.value = i;
    }

    public int getValue() {
        return this.value;
    }

    public static String getDescription(int i) {
        for (MBCanDataType mBCanDataType : values()) {
            if (mBCanDataType.value == i) {
                return mBCanDataType.name();
            }
        }
        return "未知按键";
    }
}
