package vad.dashing.tbox

const val TRUNK_DOOR_WIDGET_DATA_KEY = "trunkDoorWidget"
const val HVAC_TEMP_LEFT_WIDGET_HORIZONTAL_DATA_KEY = "hvacTempLeftWidgetHorizontal"
const val HVAC_TEMP_LEFT_WIDGET_VERTICAL_DATA_KEY = "hvacTempLeftWidgetVertical"
const val HVAC_TEMP_RIGHT_WIDGET_HORIZONTAL_DATA_KEY = "hvacTempRightWidgetHorizontal"
const val HVAC_TEMP_RIGHT_WIDGET_VERTICAL_DATA_KEY = "hvacTempRightWidgetVertical"
const val HVAC_FAN_WIDGET_HORIZONTAL_DATA_KEY = "hvacFanWidgetHorizontal"
const val HVAC_FAN_WIDGET_VERTICAL_DATA_KEY = "hvacFanWidgetVertical"
const val HVAC_SYNC_WIDGET_DATA_KEY = "hvacSyncWidget"
const val HVAC_BLOW_MODE_CYCLE_WIDGET_DATA_KEY = "hvacBlowModeCycleWidget"
const val HVAC_BLOW_MODE_PANEL_WIDGET_HORIZONTAL_DATA_KEY = "hvacBlowModePanelWidgetHorizontal"
const val HVAC_BLOW_MODE_PANEL_WIDGET_VERTICAL_DATA_KEY = "hvacBlowModePanelWidgetVertical"

val HVAC_CLIMATE_WIDGET_DATA_KEYS: Set<String> = setOf(
    TRUNK_DOOR_WIDGET_DATA_KEY,
    HVAC_TEMP_LEFT_WIDGET_HORIZONTAL_DATA_KEY,
    HVAC_TEMP_LEFT_WIDGET_VERTICAL_DATA_KEY,
    HVAC_TEMP_RIGHT_WIDGET_HORIZONTAL_DATA_KEY,
    HVAC_TEMP_RIGHT_WIDGET_VERTICAL_DATA_KEY,
    HVAC_FAN_WIDGET_HORIZONTAL_DATA_KEY,
    HVAC_FAN_WIDGET_VERTICAL_DATA_KEY,
    HVAC_SYNC_WIDGET_DATA_KEY,
    HVAC_BLOW_MODE_CYCLE_WIDGET_DATA_KEY,
    HVAC_BLOW_MODE_PANEL_WIDGET_HORIZONTAL_DATA_KEY,
    HVAC_BLOW_MODE_PANEL_WIDGET_VERTICAL_DATA_KEY,
)
