package com.mengbo.mbCan.entity;

/* loaded from: classes.dex */
public class MBCanVehicleIcmDriverInfo {
    private byte nICM_ABSFailSts;
    private byte nICM_ACCmode;
    private byte nICM_AVHAvailable;
    private byte nICM_AVHWarningMessage;
    private byte nICM_AirBagFailSts;
    private byte nICM_Brakefluid;
    private byte nICM_Cameratextinfo;
    private byte nICM_CruiseControlStsForDisplay;
    private byte nICM_DistanceWarning;
    private byte nICM_EBDFailSts;
    private byte nICM_EPBDispLargeslopeparking;
    private byte nICM_EPBDispState;
    private byte nICM_EPBDispWithoutBrake;
    private byte nICM_EPSFailSts;
    private byte nICM_ESPoffSwitchStatus;
    private byte nICM_EngineOil;
    private byte nICM_GBCFailSts;
    private short nICM_GBCInfoDisplay;
    private byte nICM_GBFaultstatus;
    private byte nICM_GSMWarninfo;
    private byte nICM_HCUPTReady;
    private byte nICM_HDCFailSts;
    private byte nICM_Maintenance;
    private byte nICM_ParkLightOnWarning;
    private byte nICM_RWUCDPActive;
    private byte nICM_RecoverableFault;
    private byte nICM_SmartSystemWarning;
    private byte nICM_SmartSystemWarning1_0;
    private byte nICM_SmartSystemWarning1_3;
    private byte nICM_SmartSystemWarning2_1;
    private byte nICM_SmartSystemWarning3_0;
    private byte nICM_SmartSystemWarning3_1;
    private byte nICM_SmartSystemWarning3_2;
    private byte nICM_SmartSystemWarning4_0;
    private byte nICM_SmartSystemWarning4_2;
    private byte nICM_SmartSystemWarning4_3;
    private byte nICM_SmartSystemWarning5_0;
    private byte nICM_SmartSystemWarning5_1;
    private short nICM_TJAICATextinfo;
    private byte nICM_Textinfo;
    private byte nICM_TirePositionWarning;
    private byte nICM_VDCTCSFailSts;

    public MBCanVehicleIcmDriverInfo(byte b, byte b2, byte b3, byte b4, byte b5, byte b6, byte b7, byte b8, byte b9, byte b10, byte b11, short s, byte b12, byte b13, byte b14, byte b15, byte b16, byte b17, byte b18, byte b19, byte b20, byte b21, short s2, byte b22, byte b23, byte b24, byte b25, byte b26, byte b27, byte b28, byte b29, byte b30, byte b31, byte b32, byte b33, byte b34, byte b35, byte b36, byte b37, byte b38, byte b39, byte b40) {
        this.nICM_EPBDispState = b;
        this.nICM_EPBDispLargeslopeparking = b2;
        this.nICM_EPBDispWithoutBrake = b3;
        this.nICM_RWUCDPActive = b4;
        this.nICM_VDCTCSFailSts = b5;
        this.nICM_EBDFailSts = b6;
        this.nICM_ABSFailSts = b7;
        this.nICM_ESPoffSwitchStatus = b8;
        this.nICM_AVHWarningMessage = b9;
        this.nICM_AVHAvailable = b10;
        this.nICM_HDCFailSts = b11;
        this.nICM_GBCInfoDisplay = s;
        this.nICM_GBCFailSts = b12;
        this.nICM_GSMWarninfo = b13;
        this.nICM_GBFaultstatus = b14;
        this.nICM_Brakefluid = b15;
        this.nICM_EngineOil = b16;
        this.nICM_ACCmode = b17;
        this.nICM_DistanceWarning = b18;
        this.nICM_SmartSystemWarning1_0 = b19;
        this.nICM_Textinfo = b20;
        this.nICM_Cameratextinfo = b21;
        this.nICM_TJAICATextinfo = s2;
        this.nICM_SmartSystemWarning = b22;
        this.nICM_SmartSystemWarning5_1 = b23;
        this.nICM_SmartSystemWarning5_0 = b24;
        this.nICM_SmartSystemWarning3_2 = b25;
        this.nICM_SmartSystemWarning4_2 = b26;
        this.nICM_SmartSystemWarning3_0 = b27;
        this.nICM_SmartSystemWarning4_0 = b28;
        this.nICM_SmartSystemWarning4_3 = b29;
        this.nICM_SmartSystemWarning1_3 = b30;
        this.nICM_SmartSystemWarning2_1 = b31;
        this.nICM_SmartSystemWarning3_1 = b32;
        this.nICM_AirBagFailSts = b33;
        this.nICM_ParkLightOnWarning = b34;
        this.nICM_EPSFailSts = b35;
        this.nICM_RecoverableFault = b36;
        this.nICM_TirePositionWarning = b37;
        this.nICM_Maintenance = b38;
        this.nICM_CruiseControlStsForDisplay = b39;
        this.nICM_HCUPTReady = b40;
    }

    public String toString() {
        StringBuffer stringBuffer = new StringBuffer("MBCanVehicleIcmFaultInfo{");
        stringBuffer.append("\n nICM_EPBDispState");
        stringBuffer.append((int) this.nICM_EPBDispState);
        stringBuffer.append("\n 文字提示“驻车坡度大，请注意驻车安全”关联=");
        stringBuffer.append((int) this.nICM_EPBDispLargeslopeparking);
        stringBuffer.append("\n 文字提示“同时踩下制动踏板”关联=");
        stringBuffer.append((int) this.nICM_EPBDispWithoutBrake);
        stringBuffer.append("\n 文字提示“紧急制动开启”  0x0:no active0x1:Active");
        stringBuffer.append((int) this.nICM_RWUCDPActive);
        stringBuffer.append("\n 文字提示“请检修ESP系统”关联=");
        stringBuffer.append((int) this.nICM_VDCTCSFailSts);
        stringBuffer.append("\n 文字提示“检修制动系统”关联=");
        stringBuffer.append((int) this.nICM_EBDFailSts);
        stringBuffer.append("\n 文字提示“请检修ABS系统”关联=");
        stringBuffer.append((int) this.nICM_ABSFailSts);
        stringBuffer.append("\n 文字提示“ESP系统已手动关闭，请注意行车安全”关联=");
        stringBuffer.append((int) this.nICM_ESPoffSwitchStatus);
        stringBuffer.append("\nnICM_AVHWarningMessage=");
        stringBuffer.append((int) this.nICM_AVHWarningMessage);
        stringBuffer.append("\n 文字提示“AutoHold失效”关联 0x0:AVH Valid 0x1:AVH Invalid");
        stringBuffer.append((int) this.nICM_AVHAvailable);
        stringBuffer.append("\n 文字提示“请检修HDC系统”关联=");
        stringBuffer.append((int) this.nICM_HDCFailSts);
        stringBuffer.append("\n nICM_GBCInfoDisplay=");
        stringBuffer.append((int) this.nICM_GBCInfoDisplay);
        stringBuffer.append("\n文字提示“换挡系统故障,请联系4S店维修”关联=");
        stringBuffer.append((int) this.nICM_GBCFailSts);
        stringBuffer.append("\n 文字提示“换挡系统故障,请联系4S店维修”关联=");
        stringBuffer.append((int) this.nICM_GSMWarninfo);
        stringBuffer.append("\n nICM_GBFaultstatus=");
        stringBuffer.append((int) this.nICM_GBFaultstatus);
        stringBuffer.append("\n 文字提示“请补充制动液”关联=");
        stringBuffer.append((int) this.nICM_Brakefluid);
        stringBuffer.append("\n 文字提示“请关闭发动机检查机油液位”关联=");
        stringBuffer.append((int) this.nICM_EngineOil);
        stringBuffer.append("\n 文字提示“踩下加速踏板时,辅助驾驶无法减速”关联=");
        stringBuffer.append((int) this.nICM_ACCmode);
        stringBuffer.append("\n 文字提示“跟车过近,请注意行车安全”关联=");
        stringBuffer.append((int) this.nICM_DistanceWarning);
        stringBuffer.append("\n 文字提示“请关闭电源”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning1_0);
        stringBuffer.append("\n nICM_Textinfo=");
        stringBuffer.append((int) this.nICM_Textinfo);
        stringBuffer.append("\n nICM_Cameratextinfo=");
        stringBuffer.append((int) this.nICM_Cameratextinfo);
        stringBuffer.append("\n nICM_TJAICATextinfo=");
        stringBuffer.append((int) this.nICM_TJAICATextinfo);
        stringBuffer.append("\n 文字提示“未检测到智能钥匙”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning);
        stringBuffer.append("\n 文字提示“系统故障允许启动X次”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning5_1);
        stringBuffer.append("\n 文字提示“请检查无钥匙启动系统”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning5_0);
        stringBuffer.append("\n 文字提示“未请挂入P或N档启动”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning3_2);
        stringBuffer.append("\n 文字提示“启动请踩刹车踏板“（自动挡）/启动请踩离合踏板“（手动挡）“关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning4_2);
        stringBuffer.append("\n 文字提示“请转动方向盘解锁转向柱”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning3_0);
        stringBuffer.append("\n 文字提示“请按启动按钮重启电源“”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning4_0);
        stringBuffer.append("\n 文字提示“请挂入P档“关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning4_3);
        stringBuffer.append("\n 文字提示“请注意车内有智能钥匙”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning1_3);
        stringBuffer.append("\n 文字提示“钥匙验证成功,可以启动”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning2_1);
        stringBuffer.append("\n 文字提示“智能钥匙电量低”关联=");
        stringBuffer.append((int) this.nICM_SmartSystemWarning3_1);
        stringBuffer.append("\n 文字提示“请检修气囊”关联=");
        stringBuffer.append((int) this.nICM_AirBagFailSts);
        stringBuffer.append("\n 文字提示“请注意小灯未关”关联=");
        stringBuffer.append((int) this.nICM_ParkLightOnWarning);
        stringBuffer.append("\n 文字提示“EPS故障，请尽快去服务站检修”关联=");
        stringBuffer.append((int) this.nICM_EPSFailSts);
        stringBuffer.append("\n nICM_RecoverableFault=");
        stringBuffer.append((int) this.nICM_RecoverableFault);
        stringBuffer.append("\n nICM_TirePositionWarning=");
        stringBuffer.append((int) this.nICM_TirePositionWarning);
        stringBuffer.append("\n 文字提示“请保养车辆”关联=");
        stringBuffer.append((int) this.nICM_Maintenance);
        stringBuffer.append("\n nICM_CruiseControlStsForDisplay=");
        stringBuffer.append((int) this.nICM_CruiseControlStsForDisplay);
        stringBuffer.append("\n 文字提示“行车准备就绪”关联=");
        stringBuffer.append((int) this.nICM_HCUPTReady);
        stringBuffer.append("\n}");
        return stringBuffer.toString();
    }
}
