package vad.dashing.tbox.ui.theme

const val LIGHT_THEME_TEXT_COLOR_PRESET_1_INT = 0xFF1A1C1E.toInt()
const val LIGHT_THEME_TEXT_COLOR_PRESET_2_INT = 0xFF1A1C1E.toInt()
const val DARK_THEME_TEXT_COLOR_PRESET_1_INT = 0xFFE2E2E6.toInt()
const val DARK_THEME_TEXT_COLOR_PRESET_2_INT = 0xFFE2E2E6.toInt()

const val LIGHT_THEME_BACKGROUND_COLOR_PRESET_1_INT = 0xFFFFFFFF.toInt()
const val LIGHT_THEME_BACKGROUND_COLOR_PRESET_2_INT = 0xFFF8F9FA.toInt()
const val DARK_THEME_BACKGROUND_COLOR_PRESET_1_INT = 0xFF131C2D.toInt()
const val DARK_THEME_BACKGROUND_COLOR_PRESET_2_INT = 0xFF292F3B.toInt()

const val LIGHT_THEME_ON_SURFACE_COLOR_INT = LIGHT_THEME_TEXT_COLOR_PRESET_1_INT
const val DARK_THEME_ON_SURFACE_COLOR_INT = DARK_THEME_TEXT_COLOR_PRESET_1_INT
